---
title: "make deploy"
author: "DCGF"
date: "15 de março de 2016"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    collapsed: true
    number_sections: true
    theme: "sandstone"
    highlight: tango
    includes:
      in_header: _font_size.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Esta é a parte do **Makefile** que define o processo **make deploy**:

```makefile
deploy: ## Atualiza o qlikview, faz commit da alteração e disponibiliza o .qvw na rede da SCPPO
	@echo Recarregando dados no Qlikview...
	@qv /r Reestimativa.qvw
	@echo "Atualizando GitLab..."
	@echo "-----------------------------------------------------"
	@git add Reestimativa.qvw
	@git commit -m "Disponibiliza app Reestimativa na pasta da SCPPO"
	@git push origin master
	@git rev-parse --short HEAD > logs/commit.txt
	@echo "-----------------------------------------------------"
	@cp Reestimativa.qvw $(PATH_SCPPO)/3.Gestão\ Fiscal/3.Reestimativa/2016/!base/Reestimativa_$(DATE)_$(COMMIT).qvw
	@echo "Arquivo Reestimativa_$(DATE)_$(COMMIT).qvw criado com sucesso em $(PATH_SCPPO)/3.Gestão Fiscal/3.Reestimativa/2016/!base/"
```

1. A linha `@qv /r Reestimativa.qvw` abre, recarrega e salva o app da Reestimativa.

2. As linhas seguintes (`git add`, `git commit`) validam e salvam
   as alterações feitas ao App no sistema de controle de versão (git). O comando
   `git push` envia estas alterações para a nuvem.
   
3. `@git rev-parse --short HEAD > logs/commit.txt` salva o identificador do
   commit no arquivo *logs/commit.txt*. Este identificador é usado no nome do
   app que é copiado na pasta da rede.
   
4. `@cp Reestimativa.qvw $(PATH_SCPPO)/3.Gestão\ Fiscal/3.Reestimativa/2016/!base/Reestimativa_$(DATE)_$(COMMIT).qvw` copia o 
   app na rede. Neste comando utiliza-se a variável de ambiente `PATH_SCPPO`,
   que indica o nome da unidade de rede ("S:" ou "T:", por exemplo), a variável
   `DATE`, que registra a data corrente, e a variável `COMMIT`, que guarda o
   identificador do commit. Todas estas variáveis são definidas no início do 
   makefile.
